bpmns:
  tenants:
    - id: "lion"
      flows:
        payment-transfer: "minimal_mock_fund_transfer.{dfspid}"
    - id: "gorilla"
      flows:
        payment-transfer: "PayerFundTransfer-{dfspid}"
        outbound-transfer-request: "{ps}_flow_{ams}-{dfspid}"
    - id: "rhino"
      flows:
        payment-transfer: "minimal_mock_fund_transfer_account_lookup-{dfspid}"
        outbound-transfer-request: "minimal_mock_transfer_request-{dfspid}"
