dfspids: "gorilla,rhino,lion"

transaction-id-length: -1

timer: "PT45S"

bpmn:
  flows:
    payment-transfer: "PayerFundTransfer-{dfspid}"
    special-payment-transfer: "SpecialPayerFundTransfer-{dfspid}"
    transaction-request: "PayeeTransactionRequest-{dfspid}"
    party-registration: "PartyRegistration-{dfspid}"
    gsma-base-transaction: "gsma_base_transaction-{dfspid}"
    gsma-int-transfer: "gsma_int_transfer"
    gsma-payee-process: "gsma_payee_process"
    gsma-bill-payment: "gsma_bill_payment"
    gsma-link-based-payment: "gsma_link_transfer"
    international-remittance-payee: "international_remittance_payee_process-{dfspid}"
    international-remittance-payer: "international_remittance_payer_process-{dfspid}"
    inboundTransactionReq-flow: "{ps}_flow_{ams}-{dfspid}"

ams:
  groups:
    - identifier: "accountid"
      value: "roster"
    - identifier: "foundationalid"
      value: "paygops"
    - identifier: "default"
      value: "paygops"

rest:
  authorization:
    enabled: false
    host: http://localhost:8080
    header: "Basic Y2xpZW50Og=="

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true
logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%35.35t]){faint} %clr(%-28.28logger{28}){cyan} %clr(:){faint}%X{BUSINESS-LOG} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

springdoc:
  writer-with-order-by-keys: true

destination:
  dfspid: "lion"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "RHVViU1ip9"
  database: 1
  cacheRetencyDuration: 30 # in days
  idempotency:
    enabled: false
    keyFormat: "clientCorrelationId_tenant_api"
    apiList: "/channel/transfer,/channel/collection,/channel/gsma/transaction,/channel/transactionRequest"

bpmns:
  tenants:
    - id: "lion"
      flows:
        payment-transfer: "minimal_mock_fund_transfer.{dfspid}"
    - id: "gorilla"
      flows:
        payment-transfer: "PayerFundTransfer-{dfspid}"
        outbound-transfer-request: "{ps}_flow_{ams}-{dfspid}"
    - id: "rhino"
      flows:
        payment-transfer: "minimal_mock_fund_transfer_account_lookup-{dfspid}"
        outbound-transfer-request: "minimal_mock_transfer_request-{dfspid}"

conductor:
  server:
    host: "http://conductor-server.netflix.svc.cluster.local:8080/"
    workflow:
      version: 1

server:
  port: 8080
