kafka:
  brokers: "localhost:9092"
  consumer-group: ch1
#  To be used when auth is enabled in kafka
#  username: "admin"
#  password: "admin"


importer:
  kafka:
    topic: conductor
    reset: true
    aggreation-window-seconds: 2

datasource:
  common:
    protocol: "jdbc"
    subprotocol: "mysql"
    driverclass_name: "com.mysql.cj.jdbc.Driver"
  core:
    port: 3306
    host: "operationsmysql"
    schema: "tenants"
    username: "mifos"
    password: "password"


spring:
  profiles:
    active: "local,tenants"

server:
  port: 8080